create extension if not exists pg_trgm;

create or replace function public.is_unisafex_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select lower(coalesce(auth.jwt() ->> 'email', '')) =
    'abhishek.work962511@gmail.com';
$$;

revoke all on function public.is_unisafex_admin() from public;
grant execute on function public.is_unisafex_admin() to authenticated;

create table if not exists public.heritage_monuments (
  id bigint generated by default as identity primary key,
  source_id integer unique,
  monument_name text not null,
  locality text,
  district text,
  state_ut text not null,
  region text,
  asi_circle text,
  monument_type text,
  protection_status text,
  visitor_category text,
  description text,
  address text,
  latitude double precision,
  longitude double precision,
  image_url text,
  timings text,
  entry_fee_indian numeric(10,2),
  entry_fee_foreigner numeric(10,2),
  rating numeric(3,1) check (rating between 0 and 5),
  featured boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.monument_visitor_stats (
  id bigint generated by default as identity primary key,
  monument_name text not null,
  state_ut text,
  fiscal_year text not null default '2024-25',
  domestic_rank integer,
  domestic_visitors bigint,
  domestic_share numeric(8,3),
  foreign_rank integer,
  foreign_visitors bigint,
  foreign_share numeric(8,3),
  total_visitors bigint,
  visitor_type_category text,
  unique (monument_name, state_ut, fiscal_year)
);

create table if not exists public.state_tourism_stats (
  state_ut text primary key,
  region text,
  domestic_visits_2023_mn numeric,
  foreign_visits_2023_mn numeric,
  domestic_visits_2024_mn numeric,
  foreign_visits_2024_mn numeric,
  domestic_growth_2024 numeric,
  foreign_growth_2024 numeric,
  domestic_share_2024 numeric,
  foreign_share_2024 numeric,
  total_visits_2024_mn numeric,
  updated_at timestamptz not null default now()
);

create index if not exists heritage_monuments_state_idx
  on public.heritage_monuments (state_ut);
create index if not exists heritage_monuments_region_idx
  on public.heritage_monuments (region);
create index if not exists heritage_monuments_type_idx
  on public.heritage_monuments (monument_type);
create index if not exists heritage_monuments_active_idx
  on public.heritage_monuments (is_active);
create index if not exists heritage_monuments_name_trgm_idx
  on public.heritage_monuments using gin (monument_name gin_trgm_ops);
create index if not exists heritage_monuments_location_trgm_idx
  on public.heritage_monuments using gin (
    (coalesce(locality, '') || ' ' || coalesce(district, '') || ' ' ||
      state_ut) gin_trgm_ops
  );
create index if not exists monument_visitor_foreign_idx
  on public.monument_visitor_stats (foreign_visitors desc nulls last);

alter table public.heritage_monuments enable row level security;
alter table public.monument_visitor_stats enable row level security;
alter table public.state_tourism_stats enable row level security;

drop policy if exists heritage_monuments_public_read
  on public.heritage_monuments;
drop policy if exists heritage_monuments_admin_write
  on public.heritage_monuments;
create policy heritage_monuments_public_read
  on public.heritage_monuments
  for select
  using (is_active or public.is_unisafex_admin());
create policy heritage_monuments_admin_write
  on public.heritage_monuments
  for all
  to authenticated
  using (public.is_unisafex_admin())
  with check (public.is_unisafex_admin());

drop policy if exists monument_visitor_stats_public_read
  on public.monument_visitor_stats;
drop policy if exists monument_visitor_stats_admin_write
  on public.monument_visitor_stats;
create policy monument_visitor_stats_public_read
  on public.monument_visitor_stats for select using (true);
create policy monument_visitor_stats_admin_write
  on public.monument_visitor_stats
  for all
  to authenticated
  using (public.is_unisafex_admin())
  with check (public.is_unisafex_admin());

drop policy if exists state_tourism_stats_public_read
  on public.state_tourism_stats;
drop policy if exists state_tourism_stats_admin_write
  on public.state_tourism_stats;
create policy state_tourism_stats_public_read
  on public.state_tourism_stats for select using (true);
create policy state_tourism_stats_admin_write
  on public.state_tourism_stats
  for all
  to authenticated
  using (public.is_unisafex_admin())
  with check (public.is_unisafex_admin());

drop policy if exists tourism_places_admin_write
  on public.tourism_places;
create policy tourism_places_admin_write
  on public.tourism_places
  for all
  to authenticated
  using (public.is_unisafex_admin())
  with check (public.is_unisafex_admin());

drop trigger if exists heritage_monuments_updated_at
  on public.heritage_monuments;
create trigger heritage_monuments_updated_at
  before update on public.heritage_monuments
  for each row execute function public.handle_updated_at();

grant select on public.heritage_monuments to anon, authenticated;
grant select on public.monument_visitor_stats to anon, authenticated;
grant select on public.state_tourism_stats to anon, authenticated;
grant insert, update, delete on public.heritage_monuments to authenticated;
grant insert, update, delete on public.monument_visitor_stats to authenticated;
grant insert, update, delete on public.state_tourism_stats to authenticated;
grant insert, update, delete on public.tourism_places to authenticated;
grant usage, select on all sequences in schema public to authenticated;
